using System;
using System.IO;
using System.Threading.Tasks;
using SignalSharp.Core.Interfaces;
using SignalSharp.Core.Models;

namespace SignalSharp.Storage.Services
{
    /// <summary>
    /// Implementation of IKeyStore that stores keys in the file system.
    /// </summary>
    public class FileKeyStore : IKeyStore
    {
        private readonly string _storageDirectory;
        private readonly IJsonSerializer _jsonSerializer;
        private const string IdentityKeyId = "identity";

        /// <summary>
        /// Initializes a new instance of the <see cref="FileKeyStore"/> class.
        /// </summary>
        /// <param name="storageDirectory">The base directory where keys will be stored.</param>
        /// <param name="jsonSerializer">The JSON serializer to use for session state serialization.</param>
        /// <exception cref="ArgumentNullException">Thrown when storageDirectory or jsonSerializer is null.</exception>
        public FileKeyStore(string storageDirectory, IJsonSerializer jsonSerializer)
        {
            if (string.IsNullOrEmpty(storageDirectory))
                throw new ArgumentNullException(nameof(storageDirectory));
            if (jsonSerializer == null)
                throw new ArgumentNullException(nameof(jsonSerializer));

            _storageDirectory = storageDirectory;
            _jsonSerializer = jsonSerializer;
            Directory.CreateDirectory(_storageDirectory);
            Directory.CreateDirectory(Path.Combine(_storageDirectory, "sessions"));
        }

        /// <inheritdoc/>
        public async Task StoreKeyAsync(string keyId, byte[] key)
        {
            if (string.IsNullOrEmpty(keyId))
                throw new ArgumentNullException(nameof(keyId));
            if (key == null)
                throw new ArgumentNullException(nameof(key));

            var filePath = Path.Combine(_storageDirectory, $"{keyId}.key");
            await File.WriteAllBytesAsync(filePath, key);
        }

        /// <inheritdoc/>
        public async Task<byte[]> GetKeyAsync(string keyId)
        {
            if (string.IsNullOrEmpty(keyId))
                throw new ArgumentNullException(nameof(keyId));

            var filePath = Path.Combine(_storageDirectory, $"{keyId}.key");
            if (!File.Exists(filePath))
                return null!;

            return await File.ReadAllBytesAsync(filePath);
        }

        /// <inheritdoc/>
        public async Task DeleteKeyAsync(string keyId)
        {
            if (string.IsNullOrEmpty(keyId))
                throw new ArgumentNullException(nameof(keyId));

            var filePath = Path.Combine(_storageDirectory, $"{keyId}.key");
            if (File.Exists(filePath))
            {
                await Task.Run(() => File.Delete(filePath));
            }
        }

        /// <inheritdoc/>
        public Task<bool> KeyExistsAsync(string keyId)
        {
            if (string.IsNullOrEmpty(keyId))
                throw new ArgumentNullException(nameof(keyId));

            var filePath = Path.Combine(_storageDirectory, $"{keyId}.key");
            return Task.FromResult(File.Exists(filePath));
        }

        /// <inheritdoc/>
        public async Task<byte[]> GetIdentityKeyAsync()
        {
            return await GetKeyAsync(IdentityKeyId);
        }

        /// <inheritdoc/>
        public async Task<byte[]> GenerateEphemeralKeyPairAsync()
        {
            var keyId = $"ephemeral_{Guid.NewGuid()}";
            var keyPair = new byte[32]; // This is just a placeholder. The actual key pair should be generated by the key exchange service.
            await StoreKeyAsync(keyId, keyPair);
            return keyPair;
        }

        /// <inheritdoc/>
        public async Task StoreSessionStateAsync(string sessionId, SessionState sessionState)
        {
            if (string.IsNullOrEmpty(sessionId))
                throw new ArgumentNullException(nameof(sessionId));
            if (sessionState == null)
                throw new ArgumentNullException(nameof(sessionState));

            var filePath = Path.Combine(_storageDirectory, "sessions", $"{sessionId}.json");
            var json = _jsonSerializer.Serialize(sessionState);
            await File.WriteAllTextAsync(filePath, json);
        }

        /// <inheritdoc/>
        public async Task<SessionState> GetSessionStateAsync(string sessionId)
        {
            if (string.IsNullOrEmpty(sessionId))
                throw new ArgumentNullException(nameof(sessionId));

            var filePath = Path.Combine(_storageDirectory, "sessions", $"{sessionId}.json");
            if (!File.Exists(filePath))
                return null!;

            var json = await File.ReadAllTextAsync(filePath);
            return _jsonSerializer.Deserialize<SessionState>(json);
        }

        /// <inheritdoc/>
        public async Task DeleteSessionStateAsync(string sessionId)
        {
            if (string.IsNullOrEmpty(sessionId))
                throw new ArgumentNullException(nameof(sessionId));

            var filePath = Path.Combine(_storageDirectory, "sessions", $"{sessionId}.json");
            if (File.Exists(filePath))
            {
                await Task.Run(() => File.Delete(filePath));
            }
        }
    }
} 