using SignalSharp.Security.Services;

namespace SignalSharp.Tests.Security
{
    /// <summary>
    /// Test suite for the HashService which provides cryptographic hashing operations for the Signal protocol.
    /// </summary>
    /// <remarks>
    /// These tests verify that the HashService correctly implements:
    /// - Standard cryptographic hashing (SHA-256)
    /// - Keyed hashing with HMAC-SHA256 for message authentication
    /// - Hash verification for data integrity
    /// - Proper input validation for all operations
    /// 
    /// Cryptographic hashing is fundamental to the Signal protocol's security,
    /// providing data integrity verification, key derivation, and message authentication.
    /// </remarks>
    public class HashServiceTests
    {
        /// <summary>
        /// The HashService instance being tested.
        /// </summary>
        private readonly HashService _hashService;

        // ReSharper disable once ConvertConstructorToMemberInitializers
        /// <summary>
        /// Initializes a new instance of the HashServiceTests class.
        /// Creates a fresh HashService instance for each test.
        /// </summary>
        public HashServiceTests()
        {
            _hashService = new HashService();
        }

        /// <summary>
        /// Tests that a standard cryptographic hash can be computed from valid input data.
        /// </summary>
        /// <remarks>
        /// This test verifies that:
        /// 1. The computed hash is not null
        /// 2. The hash has the correct length (32 bytes for SHA-256)
        /// 
        /// Cryptographic hashing provides a fixed-size, deterministic representation of input data,
        /// which is used for integrity verification throughout the Signal protocol.
        /// The 32-byte output size confirms the use of SHA-256, which offers strong
        /// collision resistance suitable for security applications.
        /// </remarks>
        [Fact]
        public async Task ComputeHashAsync_WithValidData_ShouldReturnHash()
        {
            // Arrange
            byte[] data = "Hello, Signal!"u8.ToArray();

            // Act
            byte[] hash = await _hashService.ComputeHashAsync(data);

            // Assert
            Assert.NotNull(hash);
            Assert.Equal(32, hash.Length); // SHA-256 produces 32 bytes
        }

        /// <summary>
        /// Tests that attempting to hash null data throws the appropriate exception.
        /// </summary>
        /// <remarks>
        /// This test verifies proper input validation:
        /// - The service should reject null input data with an ArgumentNullException
        /// 
        /// Input validation is important for preventing potential security vulnerabilities
        /// or cryptographic failures when processing invalid inputs.
        /// </remarks>
        [Fact]
        public async Task ComputeHashAsync_WithNullData_ShouldThrowArgumentNullException()
        {
            // Arrange
            byte[]? data = null;

            // Act & Assert
            await Assert.ThrowsAsync<ArgumentNullException>(async () =>
                await _hashService.ComputeHashAsync(data!));
        }

        /// <summary>
        /// Tests that a keyed hash (HMAC) can be computed from valid data and key.
        /// </summary>
        /// <remarks>
        /// This test verifies that:
        /// 1. The computed keyed hash is not null
        /// 2. The hash has the correct length (32 bytes for HMAC-SHA256)
        /// 
        /// Keyed hashing (HMAC) provides both integrity and authenticity verification,
        /// ensuring that the data has not been modified and was generated by a party
        /// possessing the secret key. This is critical for message authentication and 
        /// tamper resistance in the Signal protocol.
        /// </remarks>
        [Fact]
        public async Task ComputeKeyedHashAsync_WithValidDataAndKey_ShouldReturnHash()
        {
            // Arrange
            byte[] data = "Hello, Signal!"u8.ToArray();
            byte[] key = "SecretKey"u8.ToArray();

            // Act
            byte[] hash = await _hashService.ComputeKeyedHashAsync(data, key);

            // Assert
            Assert.NotNull(hash);
            Assert.Equal(32, hash.Length); // HMACSHA256 produces 32 bytes
        }

        /// <summary>
        /// Tests that attempting to compute a keyed hash with null data throws the appropriate exception.
        /// </summary>
        /// <remarks>
        /// This test verifies proper input validation:
        /// - The service should reject null input data with an ArgumentNullException
        /// 
        /// Validating inputs for cryptographic operations is essential for preventing
        /// security vulnerabilities and ensuring the correctness of the operation.
        /// </remarks>
        [Fact]
        public async Task ComputeKeyedHashAsync_WithNullData_ShouldThrowArgumentNullException()
        {
            // Arrange
            byte[]? data = null;
            byte[] key = new byte[32];

            // Act & Assert
            await Assert.ThrowsAsync<ArgumentNullException>(async () =>
                await _hashService.ComputeKeyedHashAsync(data!, key));
        }

        /// <summary>
        /// Tests that attempting to compute a keyed hash with a null key throws the appropriate exception.
        /// </summary>
        /// <remarks>
        /// This test verifies proper input validation:
        /// - The service should reject null key data with an ArgumentNullException
        /// 
        /// The key is a critical security parameter for HMAC operations, and its 
        /// absence would completely undermine the security properties of the function.
        /// </remarks>
        [Fact]
        public async Task ComputeKeyedHashAsync_WithNullKey_ShouldThrowArgumentNullException()
        {
            // Arrange
            byte[] data = new byte[32];
            byte[]? key = null;

            // Act & Assert
            await Assert.ThrowsAsync<ArgumentNullException>(async () =>
                await _hashService.ComputeKeyedHashAsync(data, key!));
        }

        /// <summary>
        /// Tests that hash verification correctly identifies matching hashes.
        /// </summary>
        /// <remarks>
        /// This test verifies that:
        /// 1. The hash verification function returns true when the hash matches the data
        /// 
        /// Hash verification is used to ensure data integrity by confirming that 
        /// the data has not been modified since the hash was generated. This is 
        /// essential for verifying the integrity of stored or transmitted data in
        /// the Signal protocol.
        /// </remarks>
        [Fact]
        public async Task VerifyHashAsync_WithMatchingHash_ShouldReturnTrue()
        {
            // Arrange
            byte[] data = "Hello, Signal!"u8.ToArray();
            byte[] hash = await _hashService.ComputeHashAsync(data);

            // Act
            bool result = await _hashService.VerifyHashAsync(data, hash);

            // Assert
            Assert.True(result);
        }

        /// <summary>
        /// Tests that hash verification correctly identifies non-matching hashes.
        /// </summary>
        /// <remarks>
        /// This test verifies that:
        /// 1. The hash verification function returns false when the hash doesn't match the data
        /// 
        /// This test ensures that the hash verification can detect when data has been
        /// modified, which is critical for detecting tampering or corruption. Even small
        /// changes to the input data should result in verification failure.
        /// </remarks>
        [Fact]
        public async Task VerifyHashAsync_WithNonMatchingHash_ShouldReturnFalse()
        {
            // Arrange
            byte[] data = "Hello, Signal!"u8.ToArray();
            byte[] differentData = "Hello, Different!"u8.ToArray();
            byte[] hash = await _hashService.ComputeHashAsync(data);

            // Act
            bool result = await _hashService.VerifyHashAsync(differentData, hash);

            // Assert
            Assert.False(result);
        }

        /// <summary>
        /// Tests that attempting hash verification with null data throws the appropriate exception.
        /// </summary>
        /// <remarks>
        /// This test verifies proper input validation:
        /// - The service should reject null input data with an ArgumentNullException
        /// 
        /// Proper validation of inputs is essential for preventing security vulnerabilities
        /// when performing cryptographic verification operations.
        /// </remarks>
        [Fact]
        public async Task VerifyHashAsync_WithNullData_ShouldThrowArgumentNullException()
        {
            // Arrange
            byte[]? data = null;
            byte[] hash = new byte[32];

            // Act & Assert
            await Assert.ThrowsAsync<ArgumentNullException>(async () =>
                await _hashService.VerifyHashAsync(data!, hash));
        }

        /// <summary>
        /// Tests that attempting hash verification with a null hash throws the appropriate exception.
        /// </summary>
        /// <remarks>
        /// This test verifies proper input validation:
        /// - The service should reject null hash data with an ArgumentNullException
        /// 
        /// The hash value is essential for verification, and its absence would make
        /// the operation meaningless from a security perspective.
        /// </remarks>
        [Fact]
        public async Task VerifyHashAsync_WithNullHash_ShouldThrowArgumentNullException()
        {
            // Arrange
            byte[] data = new byte[32];
            byte[]? hash = null;

            // Act & Assert
            await Assert.ThrowsAsync<ArgumentNullException>(async () =>
                await _hashService.VerifyHashAsync(data, hash!));
        }

        /// <summary>
        /// Tests that keyed hash (HMAC) verification correctly identifies matching hashes.
        /// </summary>
        /// <remarks>
        /// This test verifies that:
        /// 1. The keyed hash verification function returns true when the hash matches the data and key
        /// 
        /// Keyed hash verification combines authentication and integrity verification,
        /// confirming that the data was both unmodified and generated by a party possessing
        /// the secret key. This is essential for verifying messages and preventing forgeries
        /// in the Signal protocol.
        /// </remarks>
        [Fact]
        public async Task VerifyKeyedHashAsync_WithMatchingHash_ShouldReturnTrue()
        {
            // Arrange
            byte[] data = "Hello, Signal!"u8.ToArray();
            byte[] key = "SecretKey"u8.ToArray();
            byte[] hash = await _hashService.ComputeKeyedHashAsync(data, key);

            // Act
            bool result = await _hashService.VerifyKeyedHashAsync(data, key, hash);

            // Assert
            Assert.True(result);
        }

        /// <summary>
        /// Tests that keyed hash verification correctly identifies non-matching hashes.
        /// </summary>
        /// <remarks>
        /// This test verifies that:
        /// 1. The keyed hash verification function returns false when the hash doesn't match the data
        /// 
        /// This ensures that the keyed hash verification can detect message tampering,
        /// which is critical for maintaining the integrity and authenticity of communications.
        /// The test demonstrates that even small changes to the data should result in verification failure.
        /// </remarks>
        [Fact]
        public async Task VerifyKeyedHashAsync_WithNonMatchingHash_ShouldReturnFalse()
        {
            // Arrange
            byte[] data = "Hello, Signal!"u8.ToArray();
            byte[] differentData = "Hello, Different!"u8.ToArray();
            byte[] key = "SecretKey"u8.ToArray();
            byte[] hash = await _hashService.ComputeKeyedHashAsync(data, key);

            // Act
            bool result = await _hashService.VerifyKeyedHashAsync(differentData, key, hash);

            // Assert
            Assert.False(result);
        }

        /// <summary>
        /// Tests that attempting keyed hash verification with null data throws the appropriate exception.
        /// </summary>
        /// <remarks>
        /// This test verifies proper input validation:
        /// - The service should reject null input data with an ArgumentNullException
        /// 
        /// Input validation is critical for preventing security vulnerabilities in
        /// cryptographic operations that are used for message authentication.
        /// </remarks>
        [Fact]
        public async Task VerifyKeyedHashAsync_WithNullData_ShouldThrowArgumentNullException()
        {
            // Arrange
            byte[]? data = null;
            byte[] key = new byte[32];
            byte[] hash = new byte[32];

            // Act & Assert
            await Assert.ThrowsAsync<ArgumentNullException>(async () =>
                await _hashService.VerifyKeyedHashAsync(data!, key, hash));
        }

        /// <summary>
        /// Tests that attempting keyed hash verification with a null key throws the appropriate exception.
        /// </summary>
        /// <remarks>
        /// This test verifies proper input validation:
        /// - The service should reject null key data with an ArgumentNullException
        /// 
        /// The key is a critical security parameter for HMAC verification, and its
        /// absence would completely undermine the authentication properties of the operation.
        /// </remarks>
        [Fact]
        public async Task VerifyKeyedHashAsync_WithNullKey_ShouldThrowArgumentNullException()
        {
            // Arrange
            byte[] data = new byte[32];
            byte[]? key = null;
            byte[] hash = new byte[32];

            // Act & Assert
            await Assert.ThrowsAsync<ArgumentNullException>(async () =>
                await _hashService.VerifyKeyedHashAsync(data, key!, hash));
        }

        /// <summary>
        /// Tests that attempting keyed hash verification with a null hash throws the appropriate exception.
        /// </summary>
        /// <remarks>
        /// This test verifies proper input validation:
        /// - The service should reject null hash data with an ArgumentNullException
        /// 
        /// The hash value is essential for verification, and its absence would make
        /// the authentication operation meaningless from a security perspective.
        /// </remarks>
        [Fact]
        public async Task VerifyKeyedHashAsync_WithNullHash_ShouldThrowArgumentNullException()
        {
            // Arrange
            byte[] data = new byte[32];
            byte[] key = new byte[32];
            byte[]? hash = null;

            // Act & Assert
            await Assert.ThrowsAsync<ArgumentNullException>(async () =>
                await _hashService.VerifyKeyedHashAsync(data, key, hash!));
        }
    }
}